<%!
from alembic import op
import sqlalchemy as sa
%>

-- commands auto generated by Alembic - please adjust! --

<% if len(upgrade_ops) > 0: %>
def upgrade():
    <% for op in upgrade_ops: %>
    <%= op %>
    <% endfor %>
<% else: %>
def upgrade():
    pass
<% endif %>

<% if len(downgrade_ops) > 0: %>
def downgrade():
    <% for op in downgrade_ops: %>
    <%= op %>
    <% endfor %>
<% else: %>
def downgrade():
    pass
<% endif %>